import type { SpotifyTrack, Playlist, Artist, Album, MoodHistoryEntry } from "@/types/index";

// ─── Mock Tracks ────────────────────────────────────────────────────────────
export const mockTracks: SpotifyTrack[] = [
  {
    id: "1",
    title: "Church",
    artist: "Chase Atlantic",
    album: "Part One",
    albumArt: "https://via.placeholder.com/300/1a1a2e/FF6B35?text=CA",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 220,
    mood: "chill",
    artistId: "a1",
    albumId: "al1",
    addedAt: "May 19, 2024",
  },
  {
    id: "2",
    title: "Cheques",
    artist: "Shubh",
    album: "Still Rollin",
    albumArt: "https://via.placeholder.com/300/2d1b69/FF6B35?text=SH",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 183,
    mood: "upbeat",
    artistId: "a2",
    albumId: "al2",
    addedAt: "Jun 23, 2024",
  },
  {
    id: "3",
    title: "People - Sped Up",
    artist: "Libianca",
    album: "People (Remixes)",
    albumArt: "https://via.placeholder.com/300/0d1b2a/FF6B35?text=LB",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 157,
    mood: "melancholy",
    artistId: "a3",
    albumId: "al3",
    addedAt: "May 18, 2024",
  },
  {
    id: "4",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    albumArt: "https://via.placeholder.com/300/1a0a2e/FF6B35?text=TW",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 200,
    mood: "energetic",
    artistId: "a4",
    albumId: "al4",
    addedAt: "Apr 10, 2024",
  },
  {
    id: "5",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    albumArt: "https://via.placeholder.com/300/0a1628/FF6B35?text=DL",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 203,
    mood: "happy",
    artistId: "a5",
    albumId: "al5",
    addedAt: "Mar 5, 2024",
  },
  {
    id: "6",
    title: "3 Musketeers",
    artist: "NextYoungin, ppcocaine",
    album: "3 Musketeers",
    albumArt: "https://via.placeholder.com/300/1a1a1a/FF6B35?text=3M",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 166,
    mood: "upbeat",
    artistId: "a6",
    albumId: "al6",
    addedAt: "Oct 17, 2023",
  },
  {
    id: "7",
    title: "By My Side ft. Tiara Andini",
    artist: "Zack Tabudlo, Tiara Andini",
    album: "By My Side",
    albumArt: "https://via.placeholder.com/300/0d2137/FF6B35?text=ZT",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 234,
    mood: "relaxing",
    artistId: "a7",
    albumId: "al7",
    addedAt: "Sep 22, 2023",
  },
  {
    id: "8",
    title: "Vixen",
    artist: "Nimstarr",
    album: "Vixen",
    albumArt: "https://via.placeholder.com/300/1a0d2e/FF6B35?text=NM",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 122,
    mood: "intense",
    artistId: "a8",
    albumId: "al8",
    addedAt: "Aug 14, 2023",
  },
  {
    id: "9",
    title: "Tum Hi Ho",
    artist: "Arijit Singh, Mithoon",
    album: "Aashiqui 2",
    albumArt: "https://via.placeholder.com/300/1a0a0a/FF6B35?text=AS",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 261,
    mood: "melancholy",
    artistId: "a9",
    albumId: "al9",
    addedAt: "58 minutes ago",
  },
  {
    id: "10",
    title: "Something About You",
    artist: "Eyedress, Dent May",
    album: "Something About You",
    albumArt: "https://via.placeholder.com/300/0a1a0a/FF6B35?text=ED",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 153,
    mood: "chill",
    artistId: "a10",
    albumId: "al10",
    addedAt: "Jul 1, 2023",
  },
];

// ─── Mock Recommended Songs (grid — no mood detected state) ─────────────────
export const mockRecommendedTracks: SpotifyTrack[] = [
  {
    id: "r1",
    title: "EMPIRE",
    artist: "Ogryzek",
    albumArt: "https://via.placeholder.com/300/2a1a0a/FF6B35?text=EM",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 195,
    mood: "intense",
    artistId: "a11",
    albumId: "al11",
  },
  {
    id: "r2",
    title: "MATUSHKA ULTRAFUNK",
    artist: "satirin, FUNK DEMON, EVO",
    albumArt: "https://via.placeholder.com/300/1a0a2e/FF6B35?text=MU",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 178,
    mood: "energetic",
    artistId: "a12",
    albumId: "al12",
  },
  {
    id: "r3",
    title: "FUNK INFERNAL",
    artist: "DYGO, Mxng0",
    albumArt: "https://via.placeholder.com/300/2e0a0a/FF6B35?text=FI",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 210,
    mood: "energetic",
    artistId: "a13",
    albumId: "al13",
  },
  {
    id: "r4",
    title: "FUNK UNIVERSO",
    artist: "Irokz",
    albumArt: "https://via.placeholder.com/300/0a2e1a/FF6B35?text=FU",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 188,
    mood: "upbeat",
    artistId: "a14",
    albumId: "al14",
  },
  {
    id: "r5",
    title: "BLAH!",
    artist: "H1IT, flvmey",
    albumArt: "https://via.placeholder.com/300/1a1a2e/FF6B35?text=BL",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 165,
    mood: "intense",
    artistId: "a15",
    albumId: "al15",
  },
  {
    id: "r6",
    title: "COM MEDO!",
    artist: "Sayfalse, Scythermane",
    albumArt: "https://via.placeholder.com/300/2e1a0a/FF6B35?text=CM",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 172,
    mood: "intense",
    artistId: "a16",
    albumId: "al16",
  },
  {
    id: "r7",
    title: "Manasha",
    artist: "Ashreveal",
    albumArt: "https://via.placeholder.com/300/0a1a2e/FF6B35?text=MN",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 198,
    mood: "chill",
    artistId: "a17",
    albumId: "al17",
  },
  {
    id: "r8",
    title: "DON'T STOP",
    artist: "GLXXMSTRIDER",
    albumArt: "https://via.placeholder.com/300/1a0a1a/FF6B35?text=DS",
    previewUrl: null,
    spotifyUrl: "https://open.spotify.com",
    duration: 215,
    mood: "energetic",
    artistId: "a18",
    albumId: "al18",
  },
];

// ─── Mock Playlists ──────────────────────────────────────────────────────────
export const mockPlaylists: Playlist[] = [
  {
    id: "liked",
    name: "Liked Songs",
    emoji: "💖",
    tracks: mockTracks,
    createdAt: "2024-01-01",
  },
  {
    id: "custom1",
    name: "My Custom Playlist",
    emoji: "🎵",
    coverImage: "https://via.placeholder.com/60/1a1a2e/FF6B35?text=MC",
    tracks: mockTracks.slice(0, 5),
    createdAt: "2024-03-15",
  },
  {
    id: "happy",
    name: "Happy Playlist",
    emoji: "😊",
    tracks: mockTracks.filter((t) => t.mood === "happy"),
    createdAt: "2024-02-10",
  },
  {
    id: "upbeat",
    name: "Upbeat Playlist",
    emoji: "😍",
    tracks: mockTracks.filter((t) => t.mood === "upbeat"),
    createdAt: "2024-02-12",
  },
  {
    id: "chill",
    name: "Chill Playlist",
    emoji: "😎",
    tracks: mockTracks.filter((t) => t.mood === "chill"),
    createdAt: "2024-02-14",
  },
  {
    id: "melancholy",
    name: "Melancholy Playlist",
    emoji: "😔",
    tracks: mockTracks.filter((t) => t.mood === "melancholy"),
    createdAt: "2024-02-16",
  },
  {
    id: "relaxing",
    name: "Relaxing Playlist",
    emoji: "😌",
    tracks: mockTracks.filter((t) => t.mood === "relaxing"),
    createdAt: "2024-02-18",
  },
  {
    id: "energetic",
    name: "Energetic Playlist",
    emoji: "⚡",
    tracks: mockTracks.filter((t) => t.mood === "energetic"),
    createdAt: "2024-02-20",
  },
  {
    id: "intense",
    name: "Intense Playlist",
    emoji: "😠",
    tracks: mockTracks.filter((t) => t.mood === "intense"),
    createdAt: "2024-02-22",
  },
];

// ─── Mock Artists ────────────────────────────────────────────────────────────
export const mockArtists: Artist[] = [
  {
    id: "a1",
    name: "Chase Atlantic",
    image: "https://via.placeholder.com/300/1a1a2e/FF6B35?text=CA",
    genres: ["dark pop", "alternative r&b", "indie pop"],
    followers: 4200000,
    topTracks: mockTracks.filter((t) => t.artistId === "a1"),
  },
  {
    id: "a4",
    name: "The Weeknd",
    image: "https://via.placeholder.com/300/1a0a2e/FF6B35?text=TW",
    genres: ["pop", "r&b", "synth-pop"],
    followers: 120000000,
    topTracks: mockTracks.filter((t) => t.artistId === "a4"),
  },
  {
    id: "a5",
    name: "Dua Lipa",
    image: "https://via.placeholder.com/300/0a1628/FF6B35?text=DL",
    genres: ["pop", "dance pop", "electropop"],
    followers: 85000000,
    topTracks: mockTracks.filter((t) => t.artistId === "a5"),
  },
];

export const mockFollowedArtists: Artist[] = mockArtists;

// ─── Mock Albums ─────────────────────────────────────────────────────────────
export const mockAlbums: Album[] = [
  {
    id: "al1",
    name: "Part One",
    albumArt: "https://via.placeholder.com/300/1a1a2e/FF6B35?text=P1",
    releaseYear: "2017",
    totalTracks: 6,
    artistId: "a1",
    artistName: "Chase Atlantic",
    tracks: mockTracks.filter((t) => t.albumId === "al1"),
  },
  {
    id: "al4",
    name: "After Hours",
    albumArt: "https://via.placeholder.com/300/1a0a2e/FF6B35?text=AH",
    releaseYear: "2020",
    totalTracks: 14,
    artistId: "a4",
    artistName: "The Weeknd",
    tracks: mockTracks.filter((t) => t.albumId === "al4"),
  },
  {
    id: "al5",
    name: "Future Nostalgia",
    albumArt: "https://via.placeholder.com/300/0a1628/FF6B35?text=FN",
    releaseYear: "2020",
    totalTracks: 11,
    artistId: "a5",
    artistName: "Dua Lipa",
    tracks: mockTracks.filter((t) => t.albumId === "al5"),
  },
];

export const mockSavedAlbums: Album[] = mockAlbums;

// ─── Mock Mood History ───────────────────────────────────────────────────────
export const mockMoodHistory: MoodHistoryEntry[] = [
  {
    id: "h1",
    mood: "chill",
    confidence: 68,
    timestamp: "17.34 PM",
    songsPlayed: [],
  },
  {
    id: "h2",
    mood: "chill",
    confidence: 97,
    timestamp: "22.54 PM",
    songsPlayed: [
      { id: "s1", title: "Church", artist: "Chase Atlantic", playedAt: "23.05 PM", duration: "2m 32s" },
      { id: "s2", title: "Kill Bill", artist: "SZA", playedAt: "23.07 PM", duration: "2m 32s" },
      { id: "s3", title: "Bad Guy", artist: "Billie Eilish", playedAt: "23.11 PM", duration: "3m 14s" },
    ],
  },
  {
    id: "h3",
    mood: "happy",
    confidence: 85,
    timestamp: "10.22 AM",
    songsPlayed: [
      { id: "s4", title: "Levitating", artist: "Dua Lipa", playedAt: "10.23 AM", duration: "3m 23s" },
      { id: "s5", title: "Blinding Lights", artist: "The Weeknd", playedAt: "10.27 AM", duration: "3m 20s" },
    ],
  },
  {
    id: "h4",
    mood: "happy",
    confidence: 91,
    timestamp: "14.10 PM",
    songsPlayed: [
      { id: "s6", title: "Cheques", artist: "Shubh", playedAt: "14.11 PM", duration: "3m 03s" },
    ],
  },
  {
    id: "h5",
    mood: "happy",
    confidence: 78,
    timestamp: "16.45 PM",
    songsPlayed: [],
  },
  {
    id: "h6",
    mood: "relaxing",
    confidence: 72,
    timestamp: "20.30 PM",
    songsPlayed: [
      { id: "s7", title: "By My Side", artist: "Zack Tabudlo", playedAt: "20.31 PM", duration: "3m 54s" },
    ],
  },
];

// ─── Mood summary helper ─────────────────────────────────────────────────────
export function getMoodSummary(entries: MoodHistoryEntry[]) {
  const counts: Record<string, number> = {};
  entries.forEach((e) => {
    counts[e.mood] = (counts[e.mood] || 0) + 1;
  });
  return Object.entries(counts).map(([mood, count]) => ({ mood, count }));
}
